owner: larskristianhaga
repo: uptime-monitor

sites:
  - name: haga.no
    url: https://haga.no
    maxRedirects: 10

assignees:
  - larskristianhaga

status-website:
  baseUrl: /uptime-monitor
  name: Uptime Monitor
  introTitle: Monitor for relevante sider
  navbar:
    - title: Monitor
      href: /uptime-monitor
    - title: GitHub
      href: https://github.com/larskristianhaga/uptime-monitor

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
