owner: larskristianhaga
repo: uptime-monitor

sites:
    # Trefelling
  - name: http://3fs.no
    url: http://3fs.no
  - name: https://3fs.no
    url: https://3fs.no

  - name: http://paal-erik.no
    url: http://paal-erik.no

  - name: http://trefellingspesialisten.no
    url: http://trefellingspesialisten.no

  - name: http://trefellings-spesialisten.no
    url: http://trefellings-spesialisten.no

    # Ta over
  - name: http://trefellingsspesialisten.no
    url: http://trefellingsspesialisten.no
  - name: https://trefellingsspesialisten.no
    url: https://trefellingsspesialisten.no

    # Ta over
  - name: http://haga.no
    url: http://haga.no
  - name: https://haga.no
    url: https://haga.no

  - name: http://casahaga.no
    url: http://casahaga.no
  - name: https://casahaga.no
    url: https://casahaga.no

  - name: http://laline.no
    url: http://laline.no
  - name: https://laline.no
    url: https://laline.no

status-website:
  baseUrl: /uptime-monitor
  name: Uptime Monitor
  introTitle: Monitor for relevante sider
  navbar:
    - title: Monitor
      href: /
    - title: GitHub
      href: https://github.com/larskristianhaga/uptime-monitor
