owner: larskristianhaga
repo: uptime-monitor

sites:
  - name: 3fs.no
    url: https://3fs.no

  - name: paal-erik.no
    url: http://paal-erik.no

  - name: trefellingspesialisten.no
    url: http://trefellingspesialisten.no

  - name: trefellings-spesialisten.no
    url: http://trefellings-spesialisten.no

  - name: casahaga.no
    url: https://casahaga.no

  - name: laline.no
    url: https://laline.no

status-website:
  baseUrl: /uptime-monitor
  name: Uptime Monitor
  introTitle: Monitor for relevante sider
  navbar:
    - title: Monitor
      href: /uptime-monitor
    - title: GitHub
      href: https://github.com/larskristianhaga/uptime-monitor
