owner: larskristianhaga
repo: uptime-monitor

sites:
  - name: http://3fs.no
    url: http://3fs.no
  - name: https://3fs.no
    url: https://3fs.no

  - name: http://paal-erik.no
    url: http://paal-erik.no
  - name: https://paal-erik.no
    url: https://paal-erik.no

  - name: http://trefellingspesialisten.no
    url: http://trefellingspesialisten.no
  - name: https://trefellingspesialisten.no
    url: https://trefellingspesialisten.no

  - name: http://trefellings-spesialisten.no
    url: http://trefellings-spesialisten.no
  - name: https://trefellings-spesialisten.no
    url: https://trefellings-spesialisten.no

status-website:
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Some Message
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/larskristianhaga/uptime-monitor
